version: '3.7'

services:
  postgresql:
    image: postgres:alpine
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      # из других контейнеров в общей сети нужно подключиться к postgresql:5432
      # на хосте подключаемся к localhost:54321
      - '54321:5432'
    networks:
      - postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.org
      PGADMIN_DEFAULT_PASSWORD: admin
      # PGADMIN_LISTEN_PORT: 5050
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '5050:80'
    networks:
      - pgadmin
      - postgresql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'
    networks:
      - mongodb

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis:/var/lib/redis
    ports:
      - '63791:6379'
    networks:
      - redis

volumes:
  postgresql:
  pgadmin:
  mongodb:
  redis:

networks:
  postgresql:
    driver: bridge

  pgadmin:
  mongodb:
  redis:
