version: '3.7'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      # из других контейнеров в общей сети нужно подключиться к postgres:5432
      # на хосте подключаемся к localhost:54321
      - '54321:5432'
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.org
      PGADMIN_DEFAULT_PASSWORD: admin
      # PGADMIN_LISTEN_PORT: 5050
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '5050:80'
    networks:
      - pgadmin
      - postgres

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis:/var/lib/redis
    ports:
      - '63791:6379'
    networks:
      - redis

volumes:
  postgres:
  pgadmin:
  redis:

networks:
  postgres:
    driver: bridge

  pgadmin:
  redis:
