# Переменные из `env_file` используется только при запуске контейнера. При
# сборке читается файл `.env`, если тот существует. Для сборки с произвольным
# env-файлом исп. docker-compose --env-file myenv. Т.о., запуск с произвольными
# настройками будет выглядеть так:
#
#   $ COMPOSE_ENV_FILE=/path/to/myenv docker-compose --env-file $COMPOSE_ENV_FILE up -d
#
# `.env` является лишь символической ссылкой на `default.env`. Это сделано для
# того чтобы запускать все без установки переменной COMPOSE_ENV_FILE и указания
# флага --env-file, т.е. чтобы с дефолтным пресетом все запустить выполняем:
#
#   $ docker-compose up -d
#
# Модифицируйте /etc/hosts чтобы иметь возможно обращаться к ресурсам по именам:
#
#  127.0.0.1 localhost wiki.local pgadmin.loc ...
#
version: '3.7'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    env_file: ${COMPOSE_ENV_FILE:-.env}
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    ports:
      # из других контейнеров в общей сети нужно подключиться к postgres:5432
      # на хосте подключаемся к localhost:54321
      - "${POSTGRES_PORT:-54321}:5432"
    networks:
      - postgres_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    env_file: ${COMPOSE_ENV_FILE:-.env}
    volumes:
      - pgadmin_data:/root/.pgadmin:rw
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - pgadmin_net
      - postgres_net
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.local`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"

  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: unless-stopped
    env_file: ${COMPOSE_ENV_FILE:-.env}
    volumes:
      - mysql_data:/var/lib/mysql:rw
    ports:
      - "${MYSQL_PORT:-33061}:3306"
    networks:
      - mysql_net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file: ${COMPOSE_ENV_FILE:-.env}
    volumes:
      - mongo_data:/data/db:rw
    ports:
      - "${MONGODB_PORT:-37017}:27017"
    networks:
      - mongo_net
    # Запрещаем автозапуск. См. `docker-compose --profile`
    profiles:
      - "cli-only"

  # веб-админка для mongodb
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    env_file: ${COMPOSE_ENV_FILE:-.env}
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFME_CONFIG_MONGODB_PORT: '27017'
      ME_CONFIG_MONGODB_AUTH_DATABASE: "${MONGO_INITDB_DATABASE}"
      ME_CONFIG_MONGODB_AUTH_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      ME_CONFIG_MONGODB_AUTH_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - "${MONGO_EXPRESS_PORT:-18081}:8081"
    networks:
      - mongo_express_net
      - mongo_net
      - traefik_net
    depends_on:
      - mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongo-express.rule=Host(`express.local`)"
      - "traefik.http.routers.mongo-express.entrypoints=web"
    profiles:
      - "cli-only"

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/var/lib/redis:rw
    ports:
      - "${REDIS_PORT:-63791}:6379"
    networks:
      - redis_net

  # Локальная вики
  # Чтобы заработала надо в postgres создать базу wiki
  wiki:
    image: requarks/wiki:latest
    container_name: wiki
    depends_on:
      - postgres
    restart: unless-stopped
    env_file: ${COMPOSE_ENV_FILE:-.env}
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: "${POSTGRES_USER}"
      DB_PASS: "${POSTGRES_PASSWORD}"
      DB_NAME: wiki
    ports:
      # 3000 порт по-дефолту в примерах для node.js
      - "${WIKI_PORT:-30001}:3000"
    networks:
      - wiki_net
      - postgres_net
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiki.rule=Host(`wiki.local`)"
      - "traefik.http.routers.wiki.entrypoints=web"

  notebook:
    image: 'jupyter/minimal-notebook'
    container_name: 'notebook'
    networks:
      - notebook_net
      - traefik_net
    ports:
      - '10000:8888'
    volumes:
      - notebook_data:/home/jovyan/work
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.notebook.entrypoints=web'
      - 'traefik.http.routers.notebook.rule=Host(`notebook.local`)'

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      #- "--ilog.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.network=traefik_net"
    ports:
      - "80:80"
      - "${TRAEFIK_PORT:-9080}:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik_net

volumes:
  pgdata:
  pgadmin_data:
  mysql_data:
  mongo_data:
  redis_data:
  notebook_data:

# TODO: некоторым можно добавить bridge.driver = 'local'
networks:
  postgres_net:
    name: postgres_net

  pgadmin_net:
    name: pgadmin_net

  mysql_net:
    name: mysql_net

  mongo_net:
    name: mongo_net

  mongo_express_net:
    name: mongo_express_net

  redis_net:
    name: redis_net

  wiki_net:
    name: wiki_net

  notebook_net:
    name: notebook_net

  traefik_net:
    name: traefik_net
