# Баг, если env_file имеет название отличное от `.env`.
version: '3.7'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    ports:
      # из других контейнеров в общей сети нужно подключиться к postgres:5432
      # на хосте подключаемся к localhost:54321
      - '54321:5432'
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - pgadmin:/root/.pgadmin:rw
    ports:
      - '5050:80'
    networks:
      - pgadmin
      - postgres

  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    volumes:
      - mysql:/var/lib/mysql:rw
    ports:
      - '33061:3306'
    networks:
      - mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    volumes:
      - mongodb:/data/db:rw
    ports:
      - '27017:27017'
    networks:
      - mongodb

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis:/var/lib/redis:rw
    ports:
      - '63791:6379'
    networks:
      - redis

  # Локальная вики
  wiki:
    image: requarks/wiki:latest
    container_name: wiki
    depends_on:
      - postgres
    restart: unless-stopped
    env_file: .env
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: "${POSTGRES_USER}"
      DB_PASS: "${POSTGRES_PASSWORD}"
      DB_NAME: wiki
    ports:
      - '3000:3000'
    networks:
      - wiki
      - postgres

volumes:
  pgdata:
  pgadmin:
  mysql:
  mongodb:
  redis:

networks:
  postgres:
  pgadmin:
  mysql:
  mongodb:
  redis:
  wiki:
