# Переменные из `env_file` используется только при запуске контейнера. При
# сборке читается файл `.env`, если тот существует. Для сборки с произвольным
# env-файлом исп. docker-compose --env-file myenv. Т.о., запуск с произвольными
# настройками будет выглядеть так:
#
#   $ COMPOSE_ENV_FILE=/path/to/myenv docker-compose --env-file $COMPOSE_ENV_FILE up -d
#
# `.env` является лишь символической ссылкой на `default.env`. Это сделано для
# того чтобы запускать все без установки переменной COMPOSE_ENV_FILE и указания
# флага --env-file, т.е. чтобы с дефолтным пресетом все запустить выполняем:
#
#   $ docker-compose up -d
#
version: '3.7'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    env_file: ${COMPOSE_ENV_FILE:-.env}
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    ports:
      # из других контейнеров в общей сети нужно подключиться к postgres:5432
      # на хосте подключаемся к localhost:54321
      - "${POSTGRES_PORT:-54321}:5432"
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    env_file: ${COMPOSE_ENV_FILE:-.env}
    volumes:
      - pgadmin:/root/.pgadmin:rw
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - pgadmin
      - postgres

  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: unless-stopped
    env_file: ${COMPOSE_ENV_FILE:-.env}
    volumes:
      - mysql:/var/lib/mysql:rw
    ports:
      - "${MYSQL_PORT:-33061}:3306"
    networks:
      - mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file: ${COMPOSE_ENV_FILE:-.env}
    volumes:
      - mongodb:/data/db:rw
    ports:
      - "${MONGODB_PORT:-27018}:27017"
    networks:
      - mongodb

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis:/var/lib/redis:rw
    ports:
      - "${REDIS_PORT:-63791}:6379"
    networks:
      - redis

  # Локальная вики
  # Чтобы заработала надо в postgres создать базу wiki
  wiki:
    image: requarks/wiki:latest
    container_name: wiki
    depends_on:
      - postgres
    restart: unless-stopped
    env_file: ${COMPOSE_ENV_FILE:-.env}
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: "${POSTGRES_USER}"
      DB_PASS: "${POSTGRES_PASSWORD}"
      DB_NAME: wiki
    ports:
      # 3000 порт по-дефолту в примерах для node.js
      - "${WIKI_PORT:-30001}:3000"
    networks:
      - wiki
      - postgres

volumes:
  pgdata:
  pgadmin:
  mysql:
  mongodb:
  redis:

networks:
  postgres:
  pgadmin:
  mysql:
  mongodb:
  redis:
  wiki:
